       MODULE ANISOTROPICM
       USE GLOBALM
       INTEGER    NEPK2 
       COMPLEX*16 ZOMEGAN
       REAL*8     ZW
       PARAMETER  (ZW=1./SQRT(3.0))
       REAL*8,DIMENSION(:), ALLOCATABLE:: EPK,ZEPK,ZEPKO,ZEPKN
       REAL*8,DIMENSION(:), ALLOCATABLE:: ZRQ1,ZRQ2,ZRQ3,
     &                                    ZRQ1K,ZRQ2K,ZRQ3K
       REAL*8,DIMENSION(:,:,:),ALLOCATABLE::FESS1,FESS2,FESS3
       REAL*8,DIMENSION(:,:,:),ALLOCATABLE::ZZI1,ZZI3,
     &                                      CPSI,DCDPSIL,DCDPSIL2,
     &                                      DEPSCDPSI2,
     &                                      DEPSALPHADPSI,DEPSALPHADPSI2
       REAL*8,DIMENSION(:,:,:),ALLOCATABLE::ZOMEGABP,ZOMEGABT,ZOMEGADT,
     &                                      TPSI0,TPSI0DPSI,TPSI0DLAM,
     &                                      HPSI0,HPSI0DPSI,HPSI0DLAM,
     &                                      HATJ0
       REAL*8,DIMENSION(:,:,:,:),ALLOCATABLE::ZRESU
       REAL*8,DIMENSION(:,:), ALLOCATABLE::ZDHMAXDPSI,ZDHMINMAXDPSI,
     &                                   ZDHMAXDPSI2,ZDHMINMAXDPSI2,
     &                                   HMIN3DPSI,HMIN3DPSI2,
     &                                   STYPE4,STYPE4DPSI,STYPE4DPSI2,
     &                                   RTYPE4,RTYPE4DPSI,RTYPE4DPSI2
       REAL*8,DIMENSION(:),ALLOCATABLE::ZDTK,ZDTK2,FEPK,FEPKC
       REAL*8    ZKIA(6,NSPECIES0),ZKIA1(6,NSPECIES0),ZKIA2(6,NSPECIES0)
       COMPLEX*16,DIMENSION(:),ALLOCATABLE::ZGL0PA,ZGL1PA,ZGL2PA,ZGL3PA,
     &                                      ZGL0PE,ZGL1PE,ZGL2PE,ZGL3PE,
     &                                      ZGL0DP,ZGL1DP,ZGL2DP,ZGL3DP,
     &                                  ZGL0PA1,ZGL1PA1,ZGL2PA1,ZGL3PA1,
     &                                  ZGL0PE1,ZGL1PE1,ZGL2PE1,ZGL3PE1,
     &                                  ZGL0DP1,ZGL1DP1,ZGL2DP1,ZGL3DP1
       REAl*8     ZZZI1,ZZZI3,ZZZALPHA3,RE_EMAX

C     SCALAR QUANTITIES
C$OMP THREADPRIVATE( ZOMEGAN )
C$OMP THREADPRIVATE( ZKIA,ZKIA1,ZKIA2 )
C$OMP THREADPRIVATE( ZZZI1,ZZZI3,ZZZALPHA3,RE_EMAX )

C     TENSOR QUANTITIES, TO BE ALLOCATED BOTH GLOBALLY AND
C     LOCALLY IN SUBROUTINE <ZALLOCANISO>
C$OMP THREADPRIVATE( ZRQ1,ZRQ2,ZRQ3 )
C$OMP THREADPRIVATE( ZRQ1K,ZRQ2K,ZRQ3K )
C$OMP THREADPRIVATE( FESS1,FESS2,FESS3 )
C$OMP THREADPRIVATE( ZRESU,ZEPK )
C$OMP THREADPRIVATE( ZDTK,ZDTK2,FEPK,FEPKC )
C$OMP THREADPRIVATE( ZGL0PA,ZGL1PA,ZGL2PA,ZGL3PA )
C$OMP THREADPRIVATE( ZGL0PE,ZGL1PE,ZGL2PE,ZGL3PE )
C$OMP THREADPRIVATE( ZGL0DP,ZGL1DP,ZGL2DP,ZGL3DP )
C$OMP THREADPRIVATE( ZGL0PA1,ZGL1PA1,ZGL2PA1,ZGL3PA1 )
C$OMP THREADPRIVATE( ZGL0PE1,ZGL1PE1,ZGL2PE1,ZGL3PE1 )
C$OMP THREADPRIVATE( ZGL0DP1,ZGL1DP1,ZGL2DP1,ZGL3DP1 )

       END MODULE  ANISOTROPICM
   
