C$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
C        HOW TO USE <MARS> CODE
C$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
C  0. SET SOME PARAMETERS
C     SET <RNTOR> TO STUDY <n>-MODE ->
C     SET <ROTE> TO CHANGE ROTATION AMPLITUDE ->
C
C  1. COMPUTE TROYON BETA LIMIT
C     CHANGE <PRFACT> -> 
C     RUN rexpeq -> 
C     RUN chease -> LOOK AT <BETAX>, <GEXP> ->
C     SET <IWALL=0>, <INCFEED=0> -> 
C     RUN <MARS> -> IF <ALNORM=0> THEN TROYON BETA LIMIT IS <GEXP>.
C
C  2. COMPUTE IDEAL WALL MARGINAL POSITION
C     SET <IWALL=0>, CHANGE <NV>, SET <INCFEED=0> ->
C     RUN <MARS> -> IF <ALNORM=0> THEN MARGINAL WALL POSITION IS <NV>.
C
C  3. COMPUTE EIGENVALUE WITHOUT WALL AND FEEDBACK
C     SET <IWALL=0>, <NV=maxNV>, <INCFEED=0> ->
C     RUN <MARS>
C
C  4. COMPUTE SELF- AND MUTUAL INDUCTANCES OF COILS WITHOUT WALL AND PLASMA
C     SET <NITMAX=1>, <NSWEEP=1>, <IWALL=0> ->
C     SET <INCFEED=4>, <GAINA=0>, <FEEDI=1> ->
C     RUN <MARS> -> LOOK AT <ALF> from log-file
C
C  5. COMPUTE WALL DECAY TIME
C     SET <TAUW=2E+4>, <IWALL>, <INCFEED=2>, <FEEDI=0> ->
C     RUN <MARS> -> WALL DECAY TIME = -1/<ALNORM>
C  
C  6. COMPUTE SELF-INDUCTANCE OF COILS WITH IDEAL WALL AND WITHOUT PLASMA
C     SET <TAUW=2E+14>, <IWALL>, <INCFEED=2>, <GAINA=0>, <FEEDI=1> ->
C     RUN <MARS> -> LOOK AT <ALF>
C     
C  7. RUN MARS (WITH OR WITHOUT FEEDBACK) WITH TIME EVOLUTION
C     SET <NCASE=10>, <NSWEEP=3>, <NITMAX LARGE ENOUGH>
C     SET <INCFEED=1 OR 3 OR 11>, WITH <GAINA=0, GAINH=REAL*8 FEEDBACK GAIN>
C     ISWEEP = 1: MARS EIGENVALUE PROBLEM WITHOUT FEEDBACK, OBTAIN EIGENFUNCTION
C     ISWEEP = 2: MARS TIME EVOLUTION WITHOUT FEEDBACK, UNTIL THRESHOLD 
C     ISWEEP = 3: MARS TIME EVOLUTION WITH FEEDBACK
C     RUN <MARS-F> -> FILE <TIMEEVOL> 
C
C  8. RUN MARS WITH ERROR FIELDs WITH TIME EVOLUTION 
C     SET <NCASE=20>, <NSWEEP=1>, <NITMAX LARGE ENOUGH>
C     SET <INCFEED=1 OR 3 OR 11 OR 4>, WITH <GAINA=0, GAINH=0>
C     ISWEEP = 1: MARS TIME EVOLUTION WITH EXTERNAL CURRENT SPECIFIED
C                 BY PARAMETERS EXTCURR(...)  
C     RUN <MARS-F> -> FILE <TIMEEVOL> 
C
C  9. ERROR FIELD AMPLIFICATION DUE TO EXTERNAL SOURCE CURRENT
C     SET <INCFEED=8>, <FEEDI=1.0 GIVES ERROR FIELD>
C     THE CODE RE-SETS AUTOMATICALLY THE FOLLOWING PARAMETERS:
C         <NSWEEP=1>, <GAINA=0>, <AL0=0>, <INITPE=0>
C         <NITMAX=1>
C
C  10. CARMA RUN WITH BACKWARD COUPLING: RWM GROWTH RATE
C      SET <NCOUPL=-2 OR -3>, <NV=COUPLING SURFACE POSITION>
C          <INCFEED=0>,       GET COUPLING MATRIX INPUT <BWCMAT>
C
C  11. CARMA RUN WITH BACKWARD COUPLING: RFA WITH COILS 
C      SET <NCOUPL=-2 OR -3>, <NV=COUPLING SURFACE POSITION>
C          <INCFEED=4 OR 8>,  GET COUPLING MATRIX INPUT <BWCMAT & BWCMATS>
C          <FEEDI=0>,         <NCOILT>, <NSENST>, 
C          <FEEDIT> OR USE DEFAULT TO SET N-HARMONIC
C      OUTPUT: 'CARMA SENSOR: PSIS='
C  12. FOR IPEC-LIKE IDEAL PLASMA RESPONSE W/O PLASMA FLOW, SET:
C      NCASE=2, TALPHA1=(1.,0.), DINERT=1e-6, PVISC=0., ROTE=0., 
C 
      MODULE FEEDBACKM
C$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
C----------FEEDBACK VARIABLES----------Y.Q.LIU 13/07/1999---------------
C$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
      INTEGER   NSENS0,  NCOIL0, NCOILT0, NEXTCURR
      PARAMETER(NSENS0=5,NCOIL0=6,NCOILT0=24,NEXTCURR=5)

      INTEGER   NCOIL,  NSENS,  INCFEED,        IWO,    
     I          IFEED,  KKF,    ISENS(0:NSENS0),IDYNAM,
     I          IPSIF,  ISWITCH,NCOILT,         NSENST,
     I          IBOUT,  IBOUT2, KREADECA,       KEEPTFUN,
     I          KTREST
      REAL*8    RL0,    BTCHI,  TAUF,           PHISIGN,
     R          GAINA(NCOIL0),  GAINP(NCOIL0),  PHIPHASE,
     R          HGAINA(NCOIL0), HGAINP(NCOIL0),
     R          RMFS(NCOIL0),   RLK(NCOIL0),
     R          FCCHI(NCOIL0),  FWCHI(NCOIL0),
     R          SCCHI(NCOIL0),  SWCHI(NCOIL0),  
     R          THRESHOLD, EXTCURR(NEXTCURR),   DTRAMPUI,
     R          VFMAX,FINIC
      COMPLEX*16 FNUP(0:NSENS0), FNUD(0:NSENS0),
     C          GAIN(NCOIL0),   PSITS,  
     C          OFEEDI(NCOIL0), OSENSP(NCOIL0), OSENSR(NCOIL0),
     C          FEEDI(NCOIL0),  DFEED(NCOIL0*NCOIL0),
     C          FEEDIT(NCOILT0)
      COMPLEX*16,DIMENSION(:),ALLOCATABLE::SENSNOISE
      COMPLEX*16,DIMENSION(:,:),ALLOCATABLE::CFEED,HCFEED,
     C          CFEED2,HCFEED2,
     C          BFEEDSS,BFEEDF,BFEEDST,AFEEDF,AFEEDS

      END MODULE FEEDBACKM
