      SUBROUTINE FFTOUTPT(REALV, FFTMV,  NP1, NP, NPSTRT, MEDIM, NCHI
     &                   ,KUNIT, NAME)
      CHARACTER*(*) NAME
      CHARACTER*16  FILENAM
      INTEGER    NP1, NP, NPSTRT, MEDIM, NCHI
      INTEGER    KUNITS, KUNIT
      REAL*8     REALV(NP1,NCHI)
      COMPLEX*16 FFTMV(NP1,MEDIM)

      RETURN
C
C
      WRITE(FILENAM,500) NAME
C
      OPEN(UNIT=KUNIT, FILE = FILENAM, ACCESS = 'SEQUENTIAL'
     &                ,FORM = 'FORMATTED', STATUS = 'UNKNOWN'
     &                                   , POSITION = 'APPEND')
C
      WRITE(KUNIT,1000) NAME
      WRITE(KUNIT,1010) NPSTRT,NP,NCHI
      DO JJ = NPSTRT,NP
      JJP   = JJ
      WRITE(KUNIT,1020) JJP
      WRITE(KUNIT,1030) (REALV(JJP,KK),KK = 1,NCHI)
      ENDDO
C
      WRITE(KUNIT,1110) NPSTRT,NP,MEDIM
      DO JJ = NPSTRT,NP
      JJP   = JJ
      WRITE(KUNIT,1120) JJP
      WRITE(KUNIT,1130) (REAL(FFTMV(JJP,KK)),AIMAG(FFTMV(JJP,KK))
     &                               ,KK = 1,MEDIM)
      ENDDO
C
      CLOSE(UNIT = KUNIT)
C
      RETURN
  500 FORMAT('FFT_',A,'.DAT')
 1000 FORMAT(//,1X,'REAL SPACE AND FFT FOR',1X,A8)
 1010 FORMAT( /,1X,'REAL SPACE: J = ',I5,1X,',',I5,4x,'NANGL = ',i5)
 1020 FORMAT(/,1X,'FOR J = ',I5)
 1030 FORMAT(10(1X,E12.5))
 1110 FORMAT( /,1X,'FFT  SPACE: J = ',I5,1X,',',I5,4x,'NMODE = ',i5)
 1120 FORMAT(/,1X,'FOR J = ',I5)
 1130 FORMAT(5(1X,'(',E12.5,1X,E12.5,')')) 
      END
