      MODULE            GLOBALM
      COMPLEX*16        CI,C1
      PARAMETER         (C1=1.,CI=(0.,1.))
      REAL*8            PI
      PARAMETER         (PI = 3.1415 92653 58979)
      REAL*8            B0K
      INTEGER           V2XKEY,NLAMK,NCHI0,NLAMIN,NEPK,NKL0,KNTVELL,
     &                  NKSMOOTHB,NKSMOOTHR,NKSINGULAR,KSMOOTHB,
     &                  KPROFTAUTH,KPRESSMASS
      INTEGER           NWALL0,NSMAX1,NXYCOMPS,NSPECIES0,NPICK0
      
      PARAMETER         (NWALL0=5, NSMAX1=2, NXYCOMPS=30, NSPECIES0=10,
     &                   NPICK0=20)
      LOGICAL           KEEPMO,LPROFI,DCONTI,DTERMS,OUTDAT,
     L                  DPLOLP(NXYCOMPS),DPRINT(NXYCOMPS),
     L                  INERT1,INERT2,INERT3,ODWKCOM,ISLSODE,
     L                  KVSQLIN,KVSQL(8),V2U_M0
      INTEGER           IGO,NPARAM,NSWEEP,KGAM,NNSCAN,NCONVB1,NCONVCS,
     I                  NVACJ,NUMODEL,NPROFR4,NPROFS4,OSWEEP,
     I                  NPROFN,NPROFT,NPROFR,NPROFG,NPROFIE,NPROFWE,
     I                  NPROFUI,NPROFUE,NPROFK,NPROFVD,NPROFVP,NPROFDD,
     I                  KANISOTROPIC,NPROFTTCA,NPROFTTCE,NPROFNF,
     I                  NPROFZ,
     I                  IWALL(NWALL0),IWALLJ,NWALL,MWALL,NALWALL,INCKIN,
     I                  IPARTICLE,IFOWP,IFOWT,IFOWPSI0,KFASTRUN,
     I                  NCOUPL,IPERTURB,KENORM,KEFORM,IVISC,
     I                  IDIAMV,IDIAMB,IDIAMTI,IDIAMTE,IPDIVB,JSOUT,
     I                  IOMPNUM,INORMSOL,ICALPHA2,IT_BC,ID_BC,ITSATURAT,
     I                  KNBI(NSPECIES0),K_BC_N0,KSOLTEST,
     I                  NEXPV,KSOLREAD,KSOLSAVE,MOUTPUT,INUTYPE,
     I                  NORR,NOZZ,NOPP,IORBIT,IFOW,NORB,IGAMMADIVV,
     I                  KSMTYPE4,NSPECIES,ISPECIES_F0(NSPECIES0),ISWEEP,
     I                  KNTV,KISLAND,NFLAGROTA,ZCHARGE,KEPSALPHA,
     I                  KPERTREAD,KDWKREAD,
     I                  NPICK,IPICK(NPICK0),NPROFRC,NPROFRP,NDENEQ,
     I                  KJRER,KJRE_INIT,INCDPHI
      REAL*8            ASPCT,Q0,ETA,GAMMA,NUII,PVISC,
     R                  ALPHAP,ALPHAD,ALPHAH,FRACPTH,
     R                  NUEFFIA,NUEFFEA,
     R                  P0,P0OLD,R0TYPE4,S0TYPE4,HTYPE4C,HHTYPE4C,
     R                  ETACS1,ETACS2,ETACS3,ETACS4,ETAXIS,
     R                  GAMWID,GAMQ0,TTCCONV0,TTCPARA0,TTCPERP0,
     R                  TTCINERT0,CPICK(NPICK0),
     R                  ETAI,RHO1,RHO2,SIGMA1,SIGMA2,DEXQ,DINERT,
     R                  TPOWVD,TPOWDD,PTRAPI,PTRAPH,TAUWJ,TAUW(NWALL0),
     R                  ROTE,CSROT0,OMEGA0,OMEGA1,ALPHAR,BETAR,
     R                  EQFAC,ETASTI,ETASTE,RTAN,ROTEP,
     R                  ZNE0,ZTI0,ZTE0,ZTAUA0,OMEGACI0,
     R                  TALPHA2,TALPHA3,TALPHA6,TALPHA7,TALPHA8,
     R                  CALPHA2,CALPHA3,CALPHA6,CALPHA7,CALPHA8,
     R                  TDELTAMAX,TDELTAMIN,TDELTALIM,TDELTALOW,
     R                  TCHIM0,TVPINCH0,TCHID0,TOTTIME,
     R                  CTJXB,CTNTV,CTREY,CTERGO,CTEDGE,EP_DENF0,
     R                  CDMHD,CDNTV,CDERGO,CDEDGE,SLEFT,EP_PREF0,
     R                  ADAPSDF,ADAPSD2,ADAPSLF,
     R                  ADAPSNU, ZZETA0(NSPECIES0),DZETA0(NSPECIES0),
     R                  ROTWE0,ZEFF0,DELRATS,RE_RP_FAC,ALPHACOL,
     R                  ORMIN,ORMAX,OZMIN,OZMAX,ORBE,ORBL,ORBSIGINI,
     R                  ESPECIES_Z(NSPECIES0),ESPECIES_M(NSPECIES0),
     R                  PSPECIES_AP(NSPECIES0),PSPECIES_AT(NSPECIES0),
     R                  PSPECIES_NP(NSPECIES0),PSPECIES_NTB(NSPECIES0),
     R                  PSPECIES_NTD(NSPECIES0),
     R                  PSPECIES_NDB(NSPECIES0),
     R                  PSPECIES_FOWP(NSPECIES0),
     R                  PSPECIES_FOWT(NSPECIES0),RAN_STD,OCHI0,ODJPHI,
     R                  FDIAMV,FDIAMB,FDIAMTI
      COMPLEX*16        TALPHA1,TALPHA4,TALPHA5,CALPHA1,CALPHA4,CALPHA5,
     C                  ROTEC,TOT_RJA,TOT_JRE,TOT_JPA,TOT_EPA,
     C                        COR_RJA,COR_JRE,COR_JPA,COR_EPA
C-----------------------------------------------------------------------
C  DENSITY = 1 + R*RHO1 + R*R*RHO2
C  RESISTIVITY = ETA /(1. + R*SIGMA1 +R*R*SIGMA2)
C  HERE, R = V/VTOT WHERE V IS VOLUME ENCLOSED BY FLUX SURFACE
C  RESISTIVITY IS MADE TO GO TO ZERO NEAR THE AXIS
C  GAMMA  = ADIABATIC CONSTANT (NORMALLY = 5/3)
C  GAMWID: GAMARR = GAMMA * SUM OF EXP(-((S-GAMS)/GAMWID)**4)
C  NUII   = PARALLEL VISCOSITY (R-INDEPENDENT), NEOCLASSICAL
C  PVISC  = PARALLEL VISCOSITY COEFFICIENT MULT. ABS(K-PAR) (DEFAULT = 0)
C-----------------------------------------------------------------------
      REAL*8 RNTOR,TOTDENS,JRE_SEED,JRE_EQFRAC,JRE_DIFF,JRE_EXB,
     &       V1U_DIFF
      INTEGER          M1,M2,NCOILCURR,KCOILCURR
      REAL*8           RN(NSMAX1)
      REAL*8,DIMENSION(:,:),ALLOCATABLE::RM,FFF,DFFF,COILCURR
      REAL*8,DIMENSION(:),ALLOCATABLE::COILCURR2
      REAL*8,DIMENSION(:),ALLOCATABLE::VRSJ,VRCJ,VZSJ,VZCJ,VR3J
      INTEGER,DIMENSION(:,:),ALLOCATABLE::IM
C      COMMON /COMMOD/  RM,RN,RNTOR,M1,M2,IM
C-----------------------------------------------------------------------
C  RM AND RN ARE REAL POLOIDAL AND TOROIDAL MODE NUMBERS
C-----------------------------------------------------------------------
      INTEGER,DIMENSION(:,:,:,:),ALLOCATABLE::MPLUS,MMINUS
      INTEGER,DIMENSION(NSMAX1,NSMAX1)::NPLUS,NMINUS
C-----------------------------------------------------------------------
C  MPLUS,NPLUS,MMINUS,NMINUS ARE COUPLING INDICES
C-----------------------------------------------------------------------
C
      COMPLEX*16,DIMENSION(:,:),ALLOCATABLE::V1U,V2U,V3U,B1U,
     &     B2U,B3U,J1U,J2U,J3U,J2L,PRE,PEE,PEP,PDE,PED,X1U,X2U,X3U,
     &     PPERP,PPARA,RHOP,JRE,JRE1,JRE2,JRE3,JRE2L,DPHI
C-----------------------------------------------------------------------
C      DEFINITION OF VARIABLES INSIDE PLASMA
C      =====================================
C
C      VARIABLES IN X-VECTOR
C
C  KXV1     V1U  =  S (1) COMPONENT OF CONTRAVARIANT (UP) VELOCITY
C  KXB1     B1U  =  S (1) COMPONENT OF CONTRAVARIANT (UP) MAGN.FIELD
C  KXJ2U    J2U  = CHI(2) COMPONENT OF CONTRAVARIANT (UP) CURRENT DEN
C  KXJ3     J3U  = PHI(3) COMPONENT OF CONTRAVARIANT (UP) CURRENT DEN
C  KXJ2L    J2L  = CHI(2) COMPONENT OF COVARIANT   (DOWN) CURRENT DEN
C  KXX1     X1U  =  S (1) COMPONENT OF CONTRAVARIANT (UP) DISPLACEMENT
C  KXPD     PDE  =  INTER-MEDIATE VARIABLE ~ (BEQ . grad PEE)               
C  KXPED    PED  =  INTER-MEDIATE VARIABLE ~ (PEP - PEE)
C  KXDPHI   DPHI = PERTURBED ELECTROSTATIC POTENTIAL, X-VARIABLE AS
C                     DICDATED BY MHD EQUATIONS
C
C
C      VARIABLES IN Y-VECTOR
C
C  KYV2     V2U = CHI(2) COMPONENT OF CONTRAVARIANT (UP) VELOCITY
C  KYV3     V3U = B  (3) COMPONENT OF CONTRAVARIANT (UP) VELOCITY
C  KYB2     B2U = CHI(2) COMPONENT OF CONTRAVARIANT (UP) MAGN.FIELD
C  KYB3     B3U = PHI(3) COMPONENT OF CONTRAVARIANT (UP) MAGN.FIELD
C  KYJ1     J1U =  S (1) COMPONENT OF CONTRAVARIANT (UP) CURRENT DEN
C  KYPR     PERTURBED PRESSURE FOR IONS
C  KYX2     X2U = CHI(2) COMPONENT OF CONTRAVARIANT (UP) DISPLACEMENT
C  KYPPERP  PPERP = PERPENDICULAR COMPONENT OF PERTURBED PRESSURE
C                         DUE TO KINETIC RESONANCES 
C  KYPPARA  PPARA = PARALLEL COMPONENT OF PERTURBED PRESSURE
C                         DUE TO KINETIC RESONANCES 
C  KYPE     PEE  = PERTURBED PRESSURE FOR ELECTRONS WITHIN MARS-2F
C                = PERTURBED PARALLEL PRESSURE FOR ELECTRONS 
C                  WITHIN MARS-2FK (IDIAMTE=0 & IDIAMB=1|3 & INCKIN>0)       
C  KYPP     PEP  = PERTURBED PERPENDICULAR PRESSURE FOR ELECTRONS 
C                  WITHIN MARS-2FK (IDIAMTE=0 & IDIAMB=1|3 & INCKIN>0)
C
C  KYRHOP   RHOP = PERTURBED DENSITY
C  KYX3     X3U  = X3U THIRD COMPONENT OF CONTRAVARIANT (UP) DISPLACEMENT
C
C  V1U,B1U,J2U,J3U,J2L,X1U,PDE,PED  ARE DEFINED ON THE INTEGER (CS) MESH
C  V2U,V3U,B2U,B3U,J1U,PRE,PEE,PEP,X2U,X3U,PPERP,PPARA,RHOP 
C                                   ARE DEFINED ON THE HALF   (CSM) MESH
C
      INTEGER    KXV1,KXB1,KXJ2U,KXJ3,KXJ2L,KXX1,KXPD,KXPED,KXW1,
     $           KXJRE,KXB2L,KXB3L,KXJRE2,KXJRE3,KXJRE2L,KXDPHI
      INTEGER    KYV2,KYV3,KYB2,KYB3,KYJ1,KYPR,KYPPERP,KYPPARA,KYPE,
     $           KYPP,KYRHOP,KYX2,KYX3,KYW2,KYW3,KYJRE1

C     KXJFB = KXJ2U IF RNTOR.NE.0
C     KXJFB = KXJ3  IF RNTOR.EQ.0
      INTEGER    KXJFB
C
C-----------------------------------------------------------------------
C      DEFINITION OF VARIABLES IN VACUUM
C      =================================
C
C      X-VECTOR
C
C  KXB1 = 1    B1U =  S (1) COMPONENT OF CONTRAVARIANT (UP) MAGN.FIELD
C
C      VARIABLES IN Y-VECTOR
C
C  KYB2 = 1    B2U = CHI(2) COMPONENT OF CONTRAVARIANT (UP) MAGN.FIELD
C  KYB3 = 2    B3U = PHI(3) COMPONENT OF CONTRAVARIANT (UP) MAGN.FIELD
C
C-----------------------------------------------------------------------
C
C***********************************************************************
C  SPECIFICATION OF GEOMETRY INSIDE PLASMA
C***********************************************************************
C
      REAL*8,DIMENSION(:),ALLOCATABLE::CS,CSM,CSH,RHO,RHOM,RESIST,
     &     RESISM,CSV,CSVM,Q,QM,GAMARR,GAMARM,CSE,CSEM,PEQ,PEQM,
     &     ROT,ROTM,DROT,DROTM,GMUNU,GMUNUM,TEMPE,TEMPEM,
     &     TEMPI,TEMPIM,GNUI,GNUIM,GNUE,GNUEM,JEQ,DAK,DAKM,
     &     ZEFFI,ZEFFM,
     &     DLNRHO,DLNRHOM,OMEGASI,OMEGASIM,OMEGASE,OMEGASEM,
     &     DOMEGASI,DOMEGASIM,DOMEGASE,DOMEGASEM,GNEOFUNC,GNEOFUNCM,
     &     TCHIMI,TCHIMM,TVPINCHI,TVPINCHM,TCHIDI,TCHIDM,
     &     TTCPARAI,TTCPARAM,TTCPERPI,TTCPERPM,
     &     TMOMI,TMOMM,TROTI,TROTM,TDROTI,TDROTM,TRHOI,TRHOM,
     &     QPLS,QPLSM,ROTWEI,ROTWEM,
     &     ROTEQ,ROTEQM,DROTEQ,DROTEQM,RHOEQ,RHOEQM

      REAL*8,DIMENSION(:,:,:),ALLOCATABLE::
     &                  ESPECIES_DENF,ESPECIES_PREF,ESPECIES_DEN,
     &                  ESPECIES_PRE,ESPECIES_TEM,ESPECIES_PREP
      REAL*8,DIMENSION(:,:),ALLOCATABLE::
     &                  ESPECIES_REL,ESPECIES_REE,EQJPARA,EQ1_H,EQD1_H
      INTEGER,DIMENSION(:),ALLOCATABLE::ISPECIES_EK

C-----------------------------------------------------------------------
C  CS  = INTEGER MESH
C  CSM = HALF  MESH (CS-MIDDLE)
C  CSH = LENGTH OF CSM-CELLS
C-----------------------------------------------------------------------
C     EQUILIBRIUM VARIABLES
C-----------------------------------------------------------------------
C
      COMPLEX*16,DIMENSION(:,:),ALLOCATABLE::JACOBI,JACOBM,
     &         DPEDS,DPEDSM,RPF,ZPF,RVF,ZVF,RPFM,ZPFM,RVFM,ZVFM
C-----------------------------------------------------------------------

C-----------------------------------------------------------------------
C     MATRICES FOR BACKWARD COUPLING FROM CARIDDI TO MARS
C-----------------------------------------------------------------------
C
      COMPLEX*16,DIMENSION(:,:),ALLOCATABLE::
     &      A01, A02, A11, A12, B01, B02, B11, B12, C01, C02, C11, C12,
     &      A01S,A02S,A11S,A12S,B01S,B02S,B11S,B12S,C01S,C02S,C11S,C12S
      REAL*8,DIMENSION(:),ALLOCATABLE::A00
C-----------------------------------------------------------------------
C     RADIAL LOCATION OF RATIONAL SURFACES
C     AND ADAPTIVE RADIAL MESH
C-----------------------------------------------------------------------
      INTEGER NRATSURF,KRATSURF,MRATSURF,NADAPS,KADAPS,ADAPSOPT
      INTEGER,DIMENSION(:),ALLOCATABLE::IRATSURF
C-----------------------------------------------------------------------
C     PARAMETERS FOR RMZM_F
      REAL*8  R0EXP,B0EXP,VOLTOT
      COMPLEX*16 VDEXIR,VDEXIZ

      END MODULE GLOBALM
