      MODULE GVACUUMM
      REAL*8             R0W,Z0W
      REAL*8,DIMENSION(:),ALLOCATABLE::VCS,VCSM,VCSH
C-----------------------------------------------------------------------
C  VCS  = INTEGER MESH
C  VCSM =   HALF  MESH (CS-MIDDLE)
C-----------------------------------------------------------------------
C
      COMPLEX*16,DIMENSION(:,:),ALLOCATABLE::VDG11L,VDG22L,VDG33L,
     &     VDG12L,VG11L,VG33L,VG12L,VJAC,
     &     VG22L,VG33JS,VG33JC

      COMPLEX*16,DIMENSION(:,:),ALLOCATABLE::VDG11LM,VDG22LM,VDG33LM,
     &     VDG12LM,VJACM,
     &     VG11LM,VG33LM,VG12LM,
     &     VG22LM,VG33JSM,VG33JCM

      REAL*8,DIMENSION(:,:),ALLOCATABLE::VRJA,VRJAM,
     &     VRG11L,VRG11LM,VRG12L,VRG12LM,VRG22L,VRG22LM,
     &     VRG33L,VRG33LM,VRR,VRZ,VRRM,VRZM,
     &     RWALL,ZWALL

      COMPLEX*16,DIMENSION(:),ALLOCATABLE::FGRADS

      COMPLEX*16,DIMENSION(:,:),ALLOCATABLE::ZCNDF

      REAL*8,DIMENSION(:,:),ALLOCATABLE::ZCND,ZCNDC

      END MODULE GVACUUMM
