      MODULE KINETICM
      USE GLOBALM
      INTEGER MLMAX,NCHIT,NCHI1,NCHI2,JS0

      REAL*8  PCOEFDA,PCOEFKA,PCOEFDE,PCOEFKE    
      PARAMETER ( PCOEFDA=1., PCOEFKA=-2., PCOEFDE=2., PCOEFKE=1.)

      INTEGER NDWKCOMP
      PARAMETER ( NDWKCOMP=5 )
C     FOR DIV XI TEST
C     PARAMETER ( PCOEFDA=1., PCOEFKA=0., PCOEFDE=1., PCOEFKE=0.)

      REAL*8     WK
      INTEGER    KJPKEY,KPBKEY

      INTEGER,DIMENSION(:),ALLOCATABLE::  KNUMDISTRIB
      INTEGER,DIMENSION(:,:),ALLOCATABLE::NLAMK0,NLAMK1
      REAL*8,DIMENSION(:),ALLOCATABLE::   RLM

      REAL*8,DIMENSION(:,:),ALLOCATABLE::HKMIN,HKMAX,WFUN

      REAL*8,DIMENSION(:,:),ALLOCATABLE::OMEGAE0
      REAL*8,DIMENSION(:,:,:),ALLOCATABLE::NUEFF,OMEGASN,OMEGAST,
     &       AAK,EPSLONCA,EPSALPHA,OMEGASNA,OMEGASAA,OMEGASCA,
     &       ALPHAA1,ALPHAA2,ALPHAA3,ZC1

      REAL*8,DIMENSION(:,:),ALLOCATABLE::FREQK,POSITIONKAI
      REAL*8,DIMENSION(:,:,:),ALLOCATABLE::FREQKSURF

      REAL*8,DIMENSION(:,:,:),ALLOCATABLE::BK,HK,BPK, LAMK0,LAMK1

      COMPLEX*16,DIMENSION(:,:,:),ALLOCATABLE::VX1PARA, VX1PARAM,
     &                                         VX1PERP, VX1PERPM,
     &                                         VX1DPHI, VX1DPHIM,
     &                                         VX2PARA, VX2PARAM,
     &                                         VX2PERP, VX2PERPM,
     &                                         VX2DPHI, VX2DPHIM,
     &                                         VQ1PARA, VQ1PARAM,
     &                                         VQ1PERP, VQ1PERPM,
     &                                         VQ1DPHI, VQ1DPHIM,
     &                                         VQ2PARA, VQ2PARAM,
     &                                         VQ2PERP, VQ2PERPM,
     &                                         VQ2DPHI, VQ2DPHIM,
     &                                         VQ3PARA, VQ3PARAM,
     &                                         VQ3PERP, VQ3PERPM,
     &                                         VQ3DPHI, VQ3DPHIM,
     &                                         VDPPARA, VDPPARAM,
     &                                         VDPPERP, VDPPERPM,
     &                                         VDPDPHI, VDPDPHIM

      COMPLEX*16,DIMENSION(:,:,:),ALLOCATABLE::VX1PARE, VX1PAREM,
     &                                         VX1PERE, VX1PEREM,
     &                                         VX2PARE, VX2PAREM,
     &                                         VX2PERE, VX2PEREM,
     &                                         VQ1PARE, VQ1PAREM,
     &                                         VQ1PERE, VQ1PEREM,
     &                                         VQ2PARE, VQ2PAREM,
     &                                         VQ2PERE, VQ2PEREM,
     &                                         VQ3PARE, VQ3PAREM,
     &                                         VQ3PERE, VQ3PEREM,
     &                                         VDPPARE, VDPPAREM,
     &                                         VDPPERE, VDPPEREM

C     VARIABLES FOR OUTPUTTING DWK COMPONENTS
      INTEGER,DIMENSION(:,:),ALLOCATABLE::	   INDXDWKC
      COMPLEX*16,DIMENSION(:,:,:),ALLOCATABLE::VX1PARAC, VX1PERPC,
     &                                         VX2PARAC, VX2PERPC,
     &                                         VQ1PARAC, VQ1PERPC,
     &                                         VQ2PARAC, VQ2PERPC, 
     &                                         VQ3PARAC, VQ3PERPC
	 
C     VARIABLES OF TEMPORARY CHARACTER
      REAL*8 CHIL,CHIU,HPL,HPU,LAM,OMEGAB,DRIFT,RCHIH,RQK,RDPSIK,RQ3K,
     &       RCHIHK,RSS,RUU,RUU2,TPSI0F,HPSI0F,HATJ0F,TPSI0L,TPSI0DPSIL,
     &       TPSI0DLAML,HPSI0L,HPSI0DPSIL,HPSI0DLAML

      REAL*8,DIMENSION(:),ALLOCATABLE::RCHI,RCHI2,RW1,RW2,
     &                                 RJB,RX1P,RX1B,RX1R,RX2,RQ1,RQ2,
     &                                 RBT,RPHI,RDMU,RDB

      REAL*8,DIMENSION(:),ALLOCATABLE::RCHIK,RPHIK,RTK,
     &                                 RHK,RJBK,RX1PK,RX1BK,RX1RK,
     &                                 RX2K,RQ1K,RQ2K,RVALK

      REAL*8,DIMENSION(:),ALLOCATABLE::RCHIN,RVALN,RHN

      COMPLEX*16,DIMENSION(:,:),ALLOCATABLE::
     &       V1PK, V2PK, V3PK, VKOX1A, VKOX1E, VKOQ1, VKOQ2, VKOQ3,
     &       V1PKM,V2PKM,V3PKM,VKOX1AM,VKOX1EM,VKOQ1M,VKOQ2M,VKOQ3M

      COMPLEX*16,DIMENSION(:,:,:),ALLOCATABLE::VI,VI1,VI2,VI3
      COMPLEX*16,DIMENSION(:,:),ALLOCATABLE::VPARA,VPERP,VDPHI,
     &                                       VX1,VX2,VQ1,VQ2,VQ3,VDP 

C     ADDITIONAL VARIABLES DUE TO FOW
      COMPLEX*16,DIMENSION(:,:),ALLOCATABLE::VPARA1,VPERP1,VDPHI1,
     &                          VX11,VX21,VQ11,VQ21,VQ31,VDP1
      COMPLEX*16,DIMENSION(:),ALLOCATABLE::VX1LNP,VX2LNP,
     &                          VQ1LNP,VQ2LNP,VQ3LNP,VDPLNP
      
C     VARIABLES FOR SPECIAL TREATMENT AT DRIFT=0
      COMPLEX*16 VI0(4,NSPECIES0),VI01(4,NSPECIES0),
     &           VI02(4,NSPECIES0),VI03(4,NSPECIES0)
      REAL*8     DPRM
      REAL*8,DIMENSION(:),ALLOCATABLE::LAMM,LAMHH,LAMTMP
      COMPLEX*16,DIMENSION(:,:),ALLOCATABLE::VPARA0,VPERP0,VDPHI0,
     &                       VX10,VX20,VQ10,VQ20,VQ30,VDP0  

C     ADDITIONAL VARIABLES DUE TO FOW
      COMPLEX*16,DIMENSION(:,:),ALLOCATABLE::VPARA01,VPERP01,VDPHI01,
     &                       VX101,VX201,VQ101,VQ201,VQ301,VDP01 

C     TEMPORARY VARIABLES TO SPEED UP COMPUTATIONS IN KG() AND KH()
      REAL*8,DIMENSION(:),ALLOCATABLE::RVAK1,RVAK2,RVAK3,RVAK4,RVAK5,
     &                                 RVAK6,RVAK7

C     VARIABLES DUE TO ANALYTIC SUBTRACTION OF SINGULARITIES IN 
C     PARTICLE PHASE SPACE INTEGRATION
      REAL*8 SLAMD0
      REAL*8,DIMENSION(:,:),ALLOCATABLE::SLAM0
      COMPLEX*16,DIMENSION(:,:,:),ALLOCATABLE::SVPARA0,SVPARA01,
     &                                         SVPERP0,SVPERP01,
     &                                         SVDPHI0,SVDPHI01
      COMPLEX*16,DIMENSION(:,:,:),ALLOCATABLE::SVX10,SVX101,
     &       SVX20,SVX201,SVQ10,SVQ101,SVQ20,SVQ201,SVQ30,SVQ301,
     &       SVDP0,SVDP01
      COMPLEX*16,DIMENSION(:,:,:,:),ALLOCATABLE::SF0

C     VARIABLES FOR PARALLEL COMPUTATON
      INTEGER PRIVATEJS
C     VARIABLES FOR DWK COMPONENTS CALCULATION
      COMPLEX*16,DIMENSION(:,:,:,:),POINTER::BUFFERT
      COMPLEX*16,DIMENSION(:,:,:,:),POINTER::BUFFER_I,BUFFERM_I,
     &                                       BUFFER_I1
C     SCALAR QUANTITIES
C$OMP THREADPRIVATE( PRIVATEJS )
C$OMP THREADPRIVATE( VI0,VI01,VI02,VI03 )
C$OMP THREADPRIVATE( DPRM )
C$OMP THREADPRIVATE( CHIL,CHIU,HPL,HPU,LAM,OMEGAB,DRIFT )
C$OMP THREADPRIVATE( TPSI0F,HPSI0F,HATJ0F,RQK )
C$OMP THREADPRIVATE( TPSI0L,TPSI0DPSIL,TPSI0DLAML )
C$OMP THREADPRIVATE( HPSI0L,HPSI0DPSIL,HPSI0DLAML )
C$OMP THREADPRIVATE( RDPSIK,RQ3K )
C$OMP THREADPRIVATE( RCHIHK,RSS,RUU,RUU2 )
C$OMP THREADPRIVATE( MLMAX,NCHIT,NCHI1,NCHI2,JS0,KNUMDISTRIB )
C$OMP THREADPRIVATE( KJPKEY,KPBKEY )
      
C$OMP THREADPRIVATE( INDXDWKC )
C$OMP THREADPRIVATE( VX1PARAC, VX1PERPC )
C$OMP THREADPRIVATE( VX2PARAC, VX2PERPC )
C$OMP THREADPRIVATE( VQ1PARAC, VQ1PERPC )
C$OMP THREADPRIVATE( VQ2PARAC, VQ2PERPC )
C$OMP THREADPRIVATE( VQ3PARAC, VQ3PERPC )
	  
C     TENSOR QUANTITIES, TO BE ALLOCATED BOTH GLOBALLY AND LOCALLY 
C     IN SUBROUTINE <ALLOCATEFORPARALLEL>
C$OMP THREADPRIVATE( LAMM,LAMHH,LAMTMP )
C$OMP THREADPRIVATE( VPARA0,VPERP0,VDPHI0 )
C$OMP THREADPRIVATE( VX10,VX20,VQ10,VQ20,VQ30,VDP0 )
C$OMP THREADPRIVATE( RCHI2,RW1,RW2 )
C$OMP THREADPRIVATE( RJB,RX1P,RX1B,RX1R,RX2,RQ1,RQ2 )
C$OMP THREADPRIVATE( RBT,RPHI,RDMU,RDB )
C$OMP THREADPRIVATE( RCHIK,RPHIK,RTK )
C$OMP THREADPRIVATE( RHK,RJBK,RX1PK,RX1BK,RX1RK )
C$OMP THREADPRIVATE( RX2K,RQ1K,RQ2K,RVALK )
C$OMP THREADPRIVATE( RCHIN,RVALN,RHN )
C$OMP THREADPRIVATE( VI,VI1,VI2,VI3 )
C$OMP THREADPRIVATE( VPARA,VPERP,VDPHI )
C$OMP THREADPRIVATE( VX1,VX2,VQ1,VQ2,VQ3,VDP )
C$OMP THREADPRIVATE( VPARA1,VPERP1,VDPHI1 )
C$OMP THREADPRIVATE( VX11,VX21,VQ11,VQ21,VQ31,VDP1 )
C$OMP THREADPRIVATE( RVAK1,RVAK2,RVAK3,RVAK4,RVAK5,RVAK6,RVAK7 )
C$OMP THREADPRIVATE( VPARA01,VPERP01,VDPHI01 )
C$OMP THREADPRIVATE( VX101,VX201,VQ101,VQ201,VQ301,VDP01 )
C$OMP THREADPRIVATE( VX1LNP,VX2LNP,VQ1LNP,VQ2LNP,VQ3LNP,VDPLNP )
C$OMP THREADPRIVATE( SLAMD0,SLAM0,SF0 )
C$OMP THREADPRIVATE( SVPARA0,SVPARA01,SVPERP0,SVPERP01 )
C$OMP THREADPRIVATE( SVDPHI0,SVDPHI01 )
C$OMP THREADPRIVATE( SVX10,SVX101,SVX20,SVX201,SVDP0,SVDP01 )
C$OMP THREADPRIVATE( SVQ10,SVQ101,SVQ20,SVQ201,SVQ30,SVQ301 )

      END MODULE KINETICM
