      SUBROUTINE printatoh(A,B,C,D,E,F,G,H,MX,MY,MR,NX,NY,NR9)

      USE DIMENSIM
      USE GLOBALM
      INCLUDE 'comioc.inc'

      INTEGER MX,MY,MR,NX,NY,NR9
      COMPLEX*16 A(MX,MX,MR),B(MX,MX,MR),C(MX,MX,MR),D(MY,MY,MR),
     &             E(MX,MY,MR),F(MY,MX,MR),G(MY,MX,MR),H(MX,MY,MR)
      INTEGER IX,IY,IR1,IR2
C
      LXCOL = (NX-1)*NXCOMP
      LYCOL = (NY-1)*NYCOMP

      IF (NR9.GT.0) IR1 = NR9
      IF (NR9.GT.0) IR2 = NR9
 100  FORMAT(3I5)
 110  FORMAT(2E18.10)

      OPEN(CHOUTP,FILE='ASUBM.OUT',FORM='FORMATTED')
      REWIND(CHOUTP)
      IF (NR9.EQ.0) IR1 = 2
      IF (NR9.EQ.0) IR2 = MR
      WRITE(CHOUTP,100) MX,MX,IR2-IR1+1
      DO IR=IR1,IR2
      DO IY=1,MX
      DO IX=1,MX
         WRITE(CHOUTP,110) REAL(A(IX,IY,IR)),IMAG(A(IX,IY,IR))
      ENDDO
      ENDDO
      ENDDO
      CLOSE(CHOUTP)
 
      OPEN(CHOUTP,FILE='BSUBM.OUT',FORM='FORMATTED')
      REWIND(CHOUTP)
      IF (NR9.EQ.0) IR1 = 1
      IF (NR9.EQ.0) IR2 = MR
      WRITE(CHOUTP,100) MX,MX,IR2-IR1+1
      DO IR=IR1,IR2
      DO IY=1,MX
      DO IX=1,MX
         WRITE(CHOUTP,110) REAL(B(IX,IY,IR)),IMAG(B(IX,IY,IR))
      ENDDO
      ENDDO
      ENDDO
      CLOSE(CHOUTP)
 
      OPEN(CHOUTP,FILE='CSUBM.OUT',FORM='FORMATTED')
      REWIND(CHOUTP)
      IF (NR9.EQ.0) IR1 = 1
      IF (NR9.EQ.0) IR2 = MR-1
      WRITE(CHOUTP,100) MX,MX,IR2-IR1+1
      DO IR=IR1,IR2
      DO IY=1,MX
      DO IX=1,MX
         WRITE(CHOUTP,110) REAL(C(IX,IY,IR)),IMAG(C(IX,IY,IR))
      ENDDO
      ENDDO
      ENDDO
      CLOSE(CHOUTP)
 
      OPEN(CHOUTP,FILE='DSUBM.OUT',FORM='FORMATTED')
      REWIND(CHOUTP)
      IF (NR9.EQ.0) IR1 = 1
      IF (NR9.EQ.0) IR2 = MR-1
      WRITE(CHOUTP,100) MY,MY,IR2-IR1+1
      DO IR=IR1,IR2
      DO IY=1,MY
      DO IX=1,MY
         WRITE(CHOUTP,110) REAL(D(IX,IY,IR)),IMAG(D(IX,IY,IR))
      ENDDO
      ENDDO
      ENDDO
      CLOSE(CHOUTP)
 
      OPEN(CHOUTP,FILE='ESUBM.OUT',FORM='FORMATTED')
      REWIND(CHOUTP)
      IF (NR9.EQ.0) IR1 = 1
      IF (NR9.EQ.0) IR2 = MR-1
      WRITE(CHOUTP,100) MX,MY,IR2-IR1+1
      DO IR=IR1,IR2
      DO IY=1,MY
      DO IX=1,MX
         WRITE(CHOUTP,110) REAL(E(IX,IY,IR)),IMAG(E(IX,IY,IR))
      ENDDO
      ENDDO
      ENDDO
      CLOSE(CHOUTP)
 
      OPEN(CHOUTP,FILE='FSUBM.OUT',FORM='FORMATTED')
      REWIND(CHOUTP)
      IF (NR9.EQ.0) IR1 = 1
      IF (NR9.EQ.0) IR2 = MR-1
      WRITE(CHOUTP,100) MY,MX,IR2-IR1+1
      DO IR=IR1,IR2
      DO IY=1,MX
      DO IX=1,MY
         WRITE(CHOUTP,110) REAL(F(IX,IY,IR)),IMAG(F(IX,IY,IR))
      ENDDO
      ENDDO
      ENDDO
      CLOSE(CHOUTP)
 
      OPEN(CHOUTP,FILE='GSUBM.OUT',FORM='FORMATTED')
      REWIND(CHOUTP)
      IF (NR9.EQ.0) IR1 = 1
      IF (NR9.EQ.0) IR2 = MR-1
      WRITE(CHOUTP,100) MY,MX,IR2-IR1+1
      DO IR=IR1,IR2
      DO IY=1,MX
      DO IX=1,MY
         WRITE(CHOUTP,110) REAL(G(IX,IY,IR)),IMAG(G(IX,IY,IR))
      ENDDO
      ENDDO
      ENDDO
      CLOSE(CHOUTP)
 
      OPEN(CHOUTP,FILE='HSUBM.OUT',FORM='FORMATTED')
      REWIND(CHOUTP)
      IF (NR9.EQ.0) IR1 = 2
      IF (NR9.EQ.0) IR2 = MR
      WRITE(CHOUTP,100) MX,MY,IR2-IR1+1
      DO IR=IR1,IR2
      DO IY=1,MY
      DO IX=1,MX
         WRITE(CHOUTP,110) REAL(H(IX,IY,IR)),IMAG(H(IX,IY,IR))
      ENDDO
      ENDDO
      ENDDO
      CLOSE(CHOUTP)


      RETURN
      END
