      MODULE RCOMDM
C
      REAL*8,DIMENSION(:),ALLOCATABLE::T,TM,PPEQ,PPEQM,TP,
     &     TPM,DPSIDS,DPSIDSM,ROTP,ROTPM,RHOU,RHOUM,DRHOU,DRHOUM
C
C.....TSAVE/TMSAVE HOLD THE EQUILIBRIUM F(S) WHILE THE FEEDBACK
C.....ASSEMBLY RUNS ON THE VACUUM T=1.  SEE FEEDCTRL AND KEEPTFUN.
      REAL*8,DIMENSION(:),ALLOCATABLE::TSAVE,TMSAVE
C
      REAL*8,DIMENSION(:,:),ALLOCATABLE::REQ,REQM,ZEQ,ZEQM,RJA,
     &     RJAM,G11L,G11LM,G12L,G12LM,G22L,G22LM,G33L,G33LM,
     &     RDCDZ,RDCDZM,RDSDZ,RDSDZM,RBZ,RBZM,ROTC,ROTCM
C
      END MODULE RCOMDM
