      MODULE REORBITM

      INTEGER NREORBIT,NREEQ,NREEQ2,KRE_INIT,KRE_STEP,
     &        KRE_SIGMA0,KRE_TRACE,KRE_STEP_MAX,KRE_VAC,KRE_NMAX,
     &        NVG,NTRE,KRE1,KRE2,NRE1,NRE2,KRE_STAR,KRE_STEP_TOT,
     &        KRE_PERTURB_TIME,KRE_FLT,NPHIMAX,KRE_FO,KRE_ODE
      PARAMETER (NREEQ=5, NREEQ2=14)

      REAL*8  RE_EFIELD,RE_SAC,RE_SYNCH,RE_BREMS,RE_ATOL,
     &        RE_TIME,RE_CONST(7),RE_SP,RE_S0,RE_S0MIN,RE_S0MAX,RE_CHI0,
     &        RE_PHI0,RE_P0,RE_LAMBDA0,RE_TSTEP,RE_TIME_TOT,RE_AN,RE_CN,
     &        RE_PERTURB_MAX(10),RE_PMAX,RE_BVAC,RE_PEDGE
      COMPLEX*16 RE_PERTURB(10),RE_EIGVAL(10)
      
      REAL*8,DIMENSION(:),ALLOCATABLE::RECHI
      REAL*8 TREM1,RESM1,RECM1,REFM1,REYM1,
     &       TREM2,RESM2,RECM2,REFM2,REYM2, 
     &       TREM3,RESM3,RECM3,REFM3,REYM3,
     &       TREM4,RESM4,RECM4,REFM4,REYM4 

      INTEGER KREBT,KUTODE,KUTODEMAX
      REAL*8  TREBT,RESBT,RECBT,REFBT,RE_TRELAX

      REAL*8,DIMENSION(:),ALLOCATABLE::SCPSIP,SCT,SCPP,SCTP,SCROT,
     &                                 SCRHOU,SCETA

      REAL*8,DIMENSION(:,:),ALLOCATABLE::
     &       SPJAC,SPREQ2,SPBEQ2,SPG11,SPG12,SPG22, 
     &       SCJAC,SCREQ2,SCBEQ2,SCG11,SCG12,SCG22,
     &       VPJAC,VPREQ2,VPZEQ,VPBEQ2,VPG11,VPG12,VPG22, 
     &       VCJAC,VCREQ2,VCZEQ,VCBEQ2,VCG11,VCG12,VCG22

      REAL*8,DIMENSION(:,:),ALLOCATABLE::
     &       SCB1UR,SCB1UI,SCB2UR,SCB2UI,SCB3UR,SCB3UI,
     &       VCB1UR,VCB1UI,VCB2UR,VCB2UI,VCB3UR,VCB3UI,
     &       SCJ1UR,SCJ1UI,SCJ2UR,SCJ2UI,SCJ3UR,SCJ3UI,
     &       SCV1UR,SCV1UI,SCV2UR,SCV2UI,SCV3UR,SCV3UI

      REAL*8,DIMENSION(:,:),ALLOCATABLE::
     &       VPBV1,VPBV2,VPBV3,VPBVS,
     &       VCBV1,VCBV2,VCBV3

      REAL*8 V_LIGHT,E_E,M_E,M_I,EPSILON0,MU0
      PARAMETER (V_LIGHT = 2.99792E+8,
     &           E_E     = 1.6021917E-19,
     &           M_E     = 9.1095E-31,
     &           M_I     = 1.67261E-27,
     &           EPSILON0 = 8.8542E-12,
     &           MU0      = 1.25663706E-6) 

      REAL*8 V_ALFVEN,V_ALFVENE,OMEGA_CE,OMEGA_ALFVEN,C_VA,
     &       RE_CM,RE_CSTAR,RE_TAU,RE_EC,RE_E0,RE_T0,RE_TFAC,
     &       RE_TRAD

      REAL*8,DIMENSION(:),ALLOCATABLE::ALIMIT,RLIMIT,ZLIMIT,
     &                                 AXLIM, RXLIM, ZXLIM     
      INTEGER NBOUND,NLIMIT

      REAL*8,DIMENSION(:),    ALLOCATABLE::RNTORA
      COMPLEX*16,DIMENSION(:),ALLOCATABLE::CNEIGV
      REAL*8,DIMENSION(:,:),  ALLOCATABLE::CSA,CSAM
      REAL*8,DIMENSION(:,:,:),ALLOCATABLE::
     &       SCB1AR,SCB1AI,SCB2AR,SCB2AI,SCB3AR,SCB3AI,
     &       VCB1AR,VCB1AI,VCB2AR,VCB2AI,VCB3AR,VCB3AI,
     &       SCJ1AR,SCJ1AI,SCJ2AR,SCJ2AI,SCJ3AR,SCJ3AI,
     &       SCV1AR,SCV1AI,SCV2AR,SCV2AI,SCV3AR,SCV3AI
      COMPLEX*16,DIMENSION(:,:,:),ALLOCATABLE::
     &       B1A,B2A,B3A,J1A,J2A,J3A,V1A,V2A,V3A

      END MODULE REORBITM
