*COMDECK SPECMAT
C
      COMPLEX*16       ASUBM(MXMAX,MXMAX,*),
     &                 BSUBM(MXMAX,MXMAX,*),
     &                 CSUBM(MXMAX,MXMAX,*),
     &                 DSUBM(MYMAX,MYMAX,*),
     &                 ESUBM(MXMAX,MYMAX,*),
     &                 FSUBM(MYMAX,MXMAX,*),
     &                 GSUBM(MYMAX,MXMAX,*),
     &                 HSUBM(MXMAX,MYMAX,*)
C
C-----------------------------------------------------------------------
