      MODULE TORQUEM 

      REAL*8,DIMENSION(:),ALLOCATABLE::TORQUEJXB,TORQUENTV,TORQUEREY,
     &                                 DNTRANMHD,DNTRANNTV,
     &                                 DPTRANMHD,DPTRANNTV,
     &                                 TORQUENTVI,TORQUENTVE,
     &                                 ROTOFFSET,
     &                                 TORQUEERGO,DNTRANERGO,DPTRANERGO
      REAL*8,DIMENSION(:),ALLOCATABLE::T3A,T3B,T3C,T4A,T4B,T4C,T1E,
     &                                 D3A,D3B,D3C,D4A,D4B,D4C
      REAL*8,DIMENSION(:),ALLOCATABLE::TMOM,TMOMOLD,TITALF,DENSPUMP,
     &                                 TRHOIOLD,DITALF

      COMPLEX*16,DIMENSION(:),ALLOCATABLE::DISPNORM
      COMPLEX*16,DIMENSION(:,:),ALLOCATABLE::TQB1MAT

      COMPLEX*16,DIMENSION(:),ALLOCATABLE::TORQCROSSAB,TORQCROSSBA

      REAL*8     TTORQJXB,TTORQNTV,TTORQREY,TDNTRMHD,TDNTRNTV
      REAL*8     TTORQERGO, TDNTRERGO
      COMPLEX*16 DENSPUMPA
      INTEGER    KEYTORQ

      END MODULE TORQUEM

