C*COMDECK COMLAB
C
***********************************************************************
*                                                                     *
*     C.11         LABELS                                             *
*                                                                     *
***********************************************************************
C
         COMMON /COMLAB/
     C       LABEL1,
     C       LABEL2,
     C       LABEL3,
     C       LABEL4
C
         CHARACTER*80
     C       LABEL1,
     C       LABEL2,
     C       LABEL3,
     C       LABEL4
