% procedures of generating equivalent current
% from given error field at one surface rw1
% in the vacuum, and test the vacuum field
% generated by the equivalent surface current
% with the one computed by ERGOS

Step 1: set Mac.RunEF=1 or 3, Mac.rw=1.0385, Mac.RunB=0
        run MacMainMAST_ALL_B.m --> MacGetB1EF to
            read in the EF and created INPUT_BNM_EF.IN --> INPUT_BNM.IN
   Step 2: run MarsQ with INCFEED=4, KKF=-3, KREADEC=0, RNTOR=1, FEEDI=0, IFEED=28(ESC surface)
        --> ECA.OUT, CURHARMO.OUT
Step 3: cp  CURHARMO.OUT to  CURHARMO
        run MarsQ with INCFEED=4, KKF=-2, FEEDI=1.0
Step 4: copy BPLASMA
        set Mac.RunEF=2, Mac.rw=0.9294(q=2 rat.surf.), Mac.RunB=1
        run MacMainMAST_ALL_B.m (-->MacGetB1EF.m)
            to compare the vacuum field at the
            q=2 surface
