% get Pade approximation for coupling matrices from forward coupling scheme
% the coupling matrices are first generated by running 
% MacFcGenMatAll.m and MacFcCheckAll.m
% and stored in ITER_data_*.mat

close all

SDIR = '/.automount/funsrv1/root/home/yliu/CARIDDIcirc/DataMarsf/Forward/';
mm = [-5:9];

Smat = 'nPls';

% reading data
g0 = '1e-5';
eval(['s1=' g0 ';'])
eval(['load ' SDIR 'ITER_data_' g0 '.mat'])
eval(['A1=A' Smat ';'])

g0 = '3e-5';
eval(['s2=' g0 ';'])
eval(['load ' SDIR 'ITER_data_' g0 '.mat'])
eval(['A2=A' Smat ';'])

g0 = '1e-4';
eval(['s3=' g0 ';'])
eval(['load ' SDIR 'ITER_data_' g0 '.mat'])
eval(['A3=A' Smat ';'])

g0 = '3e-4';
eval(['s4=' g0 ';'])
eval(['load ' SDIR 'ITER_data_' g0 '.mat'])
eval(['A4=A' Smat ';'])

g0 = '1e-3';
eval(['s5=' g0 ';'])
eval(['load ' SDIR 'ITER_data_' g0 '.mat'])
eval(['A5=A' Smat ';'])

g0 = '3e-3';
eval(['s6=' g0 ';'])
eval(['load ' SDIR 'ITER_data_' g0 '.mat'])
eval(['A6=A' Smat ';'])

g0 = '1e-2';
eval(['s7=' g0 ';'])
eval(['load ' SDIR 'ITER_data_' g0 '.mat'])
eval(['A7=A' Smat ';'])

g0 = '3e-2';
eval(['s8=' g0 ';'])
eval(['load ' SDIR 'ITER_data_' g0 '.mat'])
eval(['A8=A' Smat ';'])

g0 = '1e-1';
eval(['s9=' g0 ';'])
eval(['load ' SDIR 'ITER_data_' g0 '.mat'])
eval(['A9=A' Smat ';'])

g0 = '3e-1';
eval(['s10=' g0 ';'])
eval(['load ' SDIR 'ITER_data_' g0 '.mat'])
eval(['A10=A' Smat ';'])

g0 = '1e-0';
eval(['s11=' g0 ';'])
eval(['load ' SDIR 'ITER_data_' g0 '.mat'])
eval(['A11=A' Smat ';'])

g0 = '1e+3';
eval(['s12=' g0 ';'])
eval(['load ' SDIR 'ITER_data_' g0 '.mat'])
eval(['A12=A' Smat ';'])

g0 = '1e+4';
eval(['s13=' g0 ';'])
eval(['load ' SDIR 'ITER_data_' g0 '.mat'])
eval(['A13=A' Smat ';'])

g0 = '1e+5';
eval(['s14=' g0 ';'])
eval(['load ' SDIR 'ITER_data_' g0 '.mat'])
eval(['A14=A' Smat ';'])

g0 = '1e+6';
eval(['s15=' g0 ';'])
eval(['load ' SDIR 'ITER_data_' g0 '.mat'])
eval(['A15=A' Smat ';'])

g0 = '1e+2';
eval(['s16=' g0 ';'])
eval(['load ' SDIR 'ITER_data_' g0 '.mat'])
eval(['A16=A' Smat ';'])

g0 = '1e+1';
eval(['s17=' g0 ';'])
eval(['load ' SDIR 'ITER_data_' g0 '.mat'])
eval(['A17=A' Smat ';'])

g0 = '3e+0';
eval(['s18=' g0 ';'])
eval(['load ' SDIR 'ITER_data_' g0 '.mat'])
eval(['A18=A' Smat ';'])

g0 = '3e+1';
eval(['s19=' g0 ';'])
eval(['load ' SDIR 'ITER_data_' g0 '.mat'])
eval(['A19=A' Smat ';'])

g0 = '3e+2';
eval(['s20=' g0 ';'])
eval(['load ' SDIR 'ITER_data_' g0 '.mat'])
eval(['A20=A' Smat ';'])

% plot g0-dependence for diagonal elements of A
ss = [s1 s2 s3 s4 s5 s6 s7 s8 s9 s10 s11 s18 s17 s19 s16 s20 s12 s13 s14 s15];
DA = [diag(A1) diag(A2) diag(A3) diag(A4) diag(A5) diag(A6) diag(A7) diag(A8) diag(A9) diag(A10) diag(A11) diag(A18) diag(A17) diag(A19) diag(A16) diag(A20) diag(A12) diag(A13) diag(A14) diag(A15)];
figure
semilogx(ss,real(DA)','b-o'), 

figure
semilogx(ss,imag(DA)','b-o'),

% Pade approximation: A(s) = (C1*s+C0)^{-1}(B1*s+B0)
N = size(A1,1);
E = eye(N);
A = [s1*A1 s6*A6 s9*A9
     -s1*E -s6*E -s9*E 
     -E    -E    -E];
condnumA = cond(A)
b = -[A1 A6 A9];
u = b*inv(A);
C1 = u(:,1:N);
B1 = u(:,N+1:2*N);
B0 = u(:,2*N+1:end);

% check Pade approximation
A2n = inv(C1*s2+E)*(B1*s2+B0);
A5n = inv(C1*s5+E)*(B1*s5+B0);

A2max = max(max(abs(A2)));
A2err = max(max(abs(A2-A2n)/A2max))

A5max = max(max(abs(A5)));
A5err = max(max(abs(A5-A5n)/A5max))

figure
plot(mm,diag(real(A2)),'r-o'), hold on
plot(mm,diag(real(A2n)),'b--+'), hold on

figure
plot(mm,diag(imag(A2)),'r-o'), hold on
plot(mm,diag(imag(A2n)),'b--+'), hold on

figure
plot(mm,diag(real(A5)),'r-o'), hold on
plot(mm,diag(real(A5n)),'b--+'), hold on

figure
plot(mm,diag(imag(A5)),'r-o'), hold on
plot(mm,diag(imag(A5n)),'b--+'), hold on


 


