function [R,Z] = MacGetRZ(RM,ZM)

global Mac

if Mac.Nm0~=Mac.Nm2, Mac.Nm2 = Mac.Nm0; end
 
m = [0:1:Mac.Nm2-1]';
expmchi = exp(m*Mac.chi*i);

R = real(RM(:,1:Mac.Nm2)*expmchi);
Z = real(ZM(:,1:Mac.Nm2)*expmchi);

[X,II]=min(abs(Mac.s-1.30822));
[X,JJ]=min(abs(Mac.chi-1.42673));
R_POINT=R(II,JJ)*Mac.R0EXP
Z_POINT=Z(II,JJ)*Mac.R0EXP

% save the coupling surface Mac.rs
[smin,II] = min(abs(Mac.s-Mac.rs));

tmp1 = [R(II-1,:)' Z(II-1,:)'];
tmp  = [R(II,:)' Z(II,:)'];
RZrw = [(tmp1+tmp)/2*Mac.R0EXP; tmp*Mac.R0EXP];
RZrw2= tmp*Mac.R0EXP;
Ltmp = sum(sqrt(diff(tmp(:,1)).^2+diff(tmp(:,2)).^2));
RZL  = [Ltmp]*Mac.R0EXP;


%disp(['Circumference = ' num2str(RZL*Mac.R0EXP)])

%RZrw = RZrw/Mac.R0EXP;
%RZrw2 = RZrw2/Mac.R0EXP;
save MacDataS RZrw  -ascii -double   %for CarMa

% standard output
save MacSurfS RZrw2 -ascii -double   %for error field

% output R(s) along mid-plane
JJ = 1;                     Rhfs = R(1:Mac.Ns1,JJ)*Mac.R0EXP;
JJ = round((Mac.Nchi+1)/2); Rlfs = R(1:Mac.Ns1,JJ)*Mac.R0EXP;
slfs = Mac.s(1:Mac.Ns1);
shfs = -flipud(slfs);
Rhfs = flipud(Rhfs); 
Rmid = [Rhfs(1:end-1); Rlfs];
smid = [shfs(1:end-1); slfs];
res = [smid(:) Rmid(:)];
save MacRmid.txt res -ascii -double
disp(['Major radius = ', num2str((Rlfs(end)+Rhfs(end))/2), ' [m]']);
disp(['Minor radius = ', num2str((Rlfs(end)-Rhfs(end))/2), ' [m]']);


% output of MacSurfS for coupling to DIII-D PROBE_G code
% with file name: probe.points.rz.in
NST = size(RZrw2,1);  %number of R-Z points
NSP = 24;             %number of toroidal planes where PROB_G will generate vacuum field data
fid = fopen('probe.points.rz.in','w');
fprintf(fid,'%s\n','&startptsrz');
fprintf(fid,'\n');
fprintf(fid,'%s%4i%s\n','  nptsrz  =',NST,['         ! ' int2str(NST) ' R-Z points generated by YQ Liu']);
fprintf(fid,'%s\n','  phinrz  = 0.          ! reference toroidal angle in degrees');
fprintf(fid,'%s%3i%s\n','  nphinrz =',NSP,['          ! ' int2str(NSP) ' toroidal planes starting at 0']);
fprintf(fid,'\n');
fprintf(fid,'%s\n',['  ptsrz(1:2,1:' int2str(NST) ')=']);
fprintf(fid,'%25.16e %24.16e\n',RZrw2');
fprintf(fid,'\n');
fprintf(fid,'%s\n','&END');
fclose(fid);
 

IRS = II; if IRS>Mac.Ns1; IRS=IRS-Mac.Ns1+1; end, 
disp(['Save <MacSurfS> at s=' num2str(Mac.s(II)) ' and I=' int2str(IRS)]);

% save the indicated flux surfaces
II = zeros(1,length(Mac.rw));
for j=1:length(Mac.rw)
    [smin,II(j)] = min(abs(Mac.s-Mac.rw(j)));
end

if 1==1
   hf=figure(99);
   s = Mac.s(1:Mac.Ns1);
   plot(s(1:end-1),diff(s))
end

% plot RZ coordinates
if Mac.plot_RZ>0
   figure(Mac.plot_RZ)
   %Nsn=II(end);  
   Nsn=Mac.Ns1;
   %plot(R(1:Nsn,:)'*Mac.R0EXP,Z(1:Nsn,:)'*Mac.R0EXP,'g-'), hold on,
   %plot(R(1:Nsn,:)*Mac.R0EXP,Z(1:Nsn,:)*Mac.R0EXP,'g-','LineWidth',1), hold on,

   sss = linspace(0,1,11);
   for k=1:length(sss)
       [Y,III] = min(abs(Mac.s-sss(k)));
       plot(R(III,:)*Mac.R0EXP,Z(III,:)*Mac.R0EXP,'k-','LineWidth',1), hold on,
   end     
   axis equal
   xlabel('R [m]','FontSize',16)
   ylabel('Z [m]','FontSize',16)
   %IT = [64 145]; TT=(Mac.chi(IT)+2*pi)/pi*180
   %plot(R(1:Nsn,IT)*Mac.R0EXP,Z(1:Nsn,IT)*Mac.R0EXP,'b-','LineWidth',1)
end
if Mac.plot_shape>0
   hf=figure(Mac.plot_shape);
   for j=1:length(Mac.rw)
       R1 = R(II(j),:);
       Z1 = Z(II(j),:);
       R1 = [R1 R1(1)];
       Z1 = [Z1 Z1(1)];
       plot(R1*Mac.R0EXP,Z1*Mac.R0EXP,'b-','LineWidth',3), hold on
   end
   if 1==0
      a=axis; plot([8.45 8.45],[a(3) a(4)],'k--')
   end
   Mag_Axis = [R(1,1)*Mac.R0EXP Z(1,1)*Mac.R0EXP]
   res = [R(II(j),:)'*Mac.R0EXP Z(II(j),:)'*Mac.R0EXP];

   save MacDataRw res -ascii -double
   %fill(R(II(1),:)*Mac.R0EXP,Z(II(1),:)*Mac.R0EXP,[1.0 0.85 0.2]), hold on
   
   axis equal
   xlabel('R [m]','FontSize',16,'FontWeight','Bold')
   ylabel('Z [m]','FontSize',16,'FontWeight','Bold')
   ha=get(hf,'CurrentAxes'); set(ha,'FontSize',16,'FontWeight','Bold')

   %a = axis; plot([0 0],[a(3) a(4)],'k-','LineWidth',3), hold on
end

if Mac.plot_thickness>0
   figure(Mac.plot_thickness)
   for j=2:length(Mac.rw)
       k = II(j);
       w = sqrt((R(k+1,:)-R(k-1,:)).^2 + (Z(k+1,:)-Z(k-1,:)).^2)/2;
       plot(Mac.chi,w*Mac.R0EXP,'b-','LineWidth',2), hold on
   end
   xlabel('\chi','FontSize',16)
   ylabel('wall thickness [m]','FontSize',16)
end

%save (s,R) data along outboard midplane (chi=0)
if 1==1
   JJ = round((Mac.Nchi+1)/2);
   II = 1:Mac.Ns1;
   res = [Mac.s(II) R(II,JJ)*Mac.R0EXP];
   save RLFS.txt res -ascii -double
end
